wheel_leg:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # effort_controllers/JointEffortController---velocity_controllers/JointVelocityController---
  right_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_right_leg2_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_left_leg2_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # leg controllers
  base_right_leg1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_right_leg1
    pid: {p: 55, i: 0.5, d: 0.01}
  
  base_left_leg1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_left_leg1
    pid: {p: 55, i: 0.5, d: 0.01}

  right_leg1_leg2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_right_leg1_leg2
    pid: {p: 55, i: 0.5, d: 0.01}

  left_leg1_leg2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_left_leg1_leg2
    pid: {p: 55, i: 0.5, d: 0.01}