wheel_leg:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # effort_controllers/JointEffortController---velocity_controllers/JointVelocityController---
  right_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_right_leg2_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_left_leg2_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # leg controllers
  # base_right_leg1_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_base_right_leg1
  #   pid: {p: 30, i: 2.5, d: 0.0, i_clamp_min: -10.0,i_clamp_max: 10.0,antiwindup: true}
  
  # base_left_leg1_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_base_left_leg1
  #   pid: {p: 30, i: 2.5, d: 0.0, i_clamp_min: -10.0,i_clamp_max: 10.0,antiwindup: true}

  # right_leg1_leg2_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_right_leg1_leg2
  #   pid: {p: 30, i: 2.5, d: 0.0, i_clamp_min: -10.0,i_clamp_max: 10.0,antiwindup: true}

  # left_leg1_leg2_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_left_leg1_leg2
  #   pid: {p: 30, i: 2.5, d: 0.0, i_clamp_min: -10.0,i_clamp_max: 10.0,antiwindup: true}